WELD-633 Set Precedence to 101 so this Provider can be loaded first. Having the default provided JNDI based providers load first result in a NoClassDefFoundError in Google App Engine. InitialContext is not allowed in this environment